version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ''
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - internal
    ports:
    - 5433:5432

volumes:
  pgdata:

networks:
  internal: